[build]
builder = "nixpacks"

[deploy]
startCommand = "node start.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5

[[deploy.healthchecks]]
type = "http"
path = "/health"
initialDelaySeconds = 15
